<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="DTOs\" />
    <Folder Include="UseCases\AUDIT_LOG\Commands\" />
    <Folder Include="UseCases\AUDIT_LOG\Handlers\" />
    <Folder Include="UseCases\AUDIT_LOG\Queries\" />
    <Folder Include="UseCases\EVENT\Commands\" />
    <Folder Include="UseCases\EVENT\Handlers\" />
    <Folder Include="UseCases\EVENT\Queries\" />
    <Folder Include="UseCases\RESERVATION\Commands\" />
    <Folder Include="UseCases\RESERVATION\Handlers\" />
    <Folder Include="UseCases\RESERVATION\Queries\" />
    <Folder Include="UseCases\SEAT\Commands\" />
    <Folder Include="UseCases\SEAT\Handlers\" />
    <Folder Include="UseCases\SEAT\Queries\" />
    <Folder Include="UseCases\SECTOR\Commands\" />
    <Folder Include="UseCases\SECTOR\Handlers\" />
    <Folder Include="UseCases\SECTOR\Queries\" />
    <Folder Include="UseCases\USER\Commands\" />
    <Folder Include="UseCases\USER\Handlers\" />
    <Folder Include="UseCases\USER\Queries\" />
  </ItemGroup>

</Project>
